### ISSUE TITLE
3월 TODO

### ISSUE THREAD

**Issue by choo121600** [choo121600/PersonalToDo#1]

**Comment by choo121600** [comment]
## 인공지능 동아리 Bet A
- [x] 인공지능 동아리 Bet A 활동에 도움을 줄 운영진 모집
- [x] 동아리에 기본기가 부족한 사람들을 위한 강의 동영상 찍기
  - [ ] Python
  - [ ] Numpy
  - [ ] Pandas
  - [ ] Matplotlib
  - [ ] Scikit-learn
  - [ ] Pytorch

**Comment by choo121600** [comment]
## 밸런스 캐치 프로젝트 Deadline: 3월 23일
- [x] 밸런스 게임 프로젝트에서 할당된 화면 만들기 
  - [x] 2
  - [ ] 3
  - [ ] 4
  - [ ] 5
